package agentconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/vision-mcp/internal/config"
)

func Generate(outputPath string) error {
	if outputPath == "" {
		home, _ := os.UserHomeDir()
		outputPath = filepath.Join(home, "Desktop", "vision-mcp-setup.md")
	}

	cfg, _ := config.LoadConfig()
	installDir := config.InstallDir()

	cmd := "vision-mcp"
	if runtime.GOOS == "windows" {
		cmd = filepath.Join(installDir, "vision-mcp.cmd")
	}

	content := fmt.Sprintf(`# Instructions to configure Vision MCP in your agent

This file was generated by Vision MCP Setup Wizard.
Pass it to your agent so it can configure the MCP server automatically.

## MCP Server Configuration

### Kilo Code / OpenCode format (kilo.json / opencode.json)

`+"```json"+`
{
  "mcp": {
    "vision-mcp": {
      "type": "local",
      "command": ["%s"],
      "enabled": true
    }
  }
}
`+"```"+`

### Zed Editor format (settings.json)

`+"```json"+`
{
  "context_servers": {
    "vision-mcp": {
      "command": "%s",
      "args": [],
      "env": {}
    }
  }
}
`+"```"+`

### Claude Desktop / PI Agent format (claude_desktop_config.json / mcp.json)

`+"```json"+`
{
  "mcpServers": {
    "vision-mcp": {
      "command": "%s",
      "env": {
        "VISION_MCP_PORT": "%d",
        "VISION_MCP_LLAMA_BACKEND": "%s"
      }
    }
  }
}
`+"```"+`

## Available tools

| Tool | Description |
|------|-------------|
| analyze_image(prompt, image) | Analyze an image with a custom prompt |

## Where to configure based on your agent

### Kilo Code
- File: ~/.config/kilo/kilo.json
- Add the "mcp" block above to the JSON root

### OpenCode
- File: ~/.config/opencode/opencode.json
- Add the "mcp" block above to the JSON root

### Zed Editor
- File: ~/.config/zed/settings.json (macOS/Linux) or %%APPDATA%%\Zed\settings.json (Windows)
- Add the "context_servers" block above to the JSON root

### PI Agent
- File: ~/.config/mcp/mcp.json
- Use the "mcpServers" format above

### Claude Desktop
- File: claude_desktop_config.json
- Location: %%APPDATA%%\Claude\claude_desktop_config.json
- Use the "mcpServers" format above

## Verify installation

`+"```bash"+`
vision-mcp --status
`+"```"+`
`, cmd, cmd, cmd, cfg.Port, cfg.LlamaBackend)

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write agent config: %w", err)
	}

	return nil
}
