package agentconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/vision-mcp/internal/config"
)

func Generate(outputPath string) error {
	if outputPath == "" {
		home, _ := os.UserHomeDir()
		outputPath = filepath.Join(home, "Desktop", "vision-mcp-setup.md")
	}

	cfg, _ := config.LoadConfig()
	installDir := config.InstallDir()

	cmd := "vision-mcp"
	if runtime.GOOS == "windows" {
		cmd = filepath.Join(installDir, "vision-mcp.cmd")
	}

	content := fmt.Sprintf(`# Instructions to configure Vision MCP in your agent

This file was generated by Vision MCP Setup Wizard.
Pass it to your agent so it can configure the MCP server automatically.

## MCP Server Configuration

`+"```json"+`
{
  "mcpServers": {
    "vision": {
      "command": "%s",
      "env": {
        "VISION_MCP_PORT": "%d",
        "VISION_MCP_LLAMA_BACKEND": "%s"
      }
    }
  }
}
`+"```"+`

## Available tools

| Tool | Description |
|------|-------------|
| analyze_image(prompt, image) | Analyze an image with a custom prompt |
| describe_image(image) | Describe an image in detail |

## Where to configure based on your agent

### Kilo Code
- File: /path/to/.kilocode/mcp.json
- Paste the JSON config above

### OpenCode
- File: ~/.opencode/mcp.json
- Or configure via OpenCode interface

### PI Agent
- Project configuration file
- Add to the mcpServers block

### Claude Desktop
- File: claude_desktop_config.json
- Location: %%APPDATA%%\Claude\claude_desktop_config.json

## Verify installation

`+"```bash"+`
vision-mcp --status
`+"```"+`
`, cmd, cfg.Port, cfg.LlamaBackend)

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write agent config: %w", err)
	}

	return nil
}
